export const SET_CONTACTS_DATA = 'SET_CONTACTS_DATA';
export const SET_ERROR_INFO = 'SET_ERROR_INFO';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const SET_CONTACT_ID = 'SET_CONTACT_ID';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
